### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by Noitidart** [Noitidart/jscFileWatcher#4]
- [x] Create jscFileWatcher API based on [Bugzilla :: Bug 958280 - [OS.File] Add a watch() function to OS.File - Comment 1](https://bugzilla.mozilla.org/show_bug.cgi?id=958280#c1)
- [x] Linux iNotify standalone working example (standalone means just do what it takes to get it to work)
  - [standalone example](https://github.com/Noitidart/jscFileWatcher/blob/25a84c4ba54baea24b599518e5de4dda47983629/modules/workers/myWorker.js#L147-164)
- [x] Merge Linux iNotify based on working example to jscFileWatcher API
- [x] kqueue standalone working example for *bsd and osx < 10.7
  - [stand alone example](https://github.com/Noitidart/jscFileWatcher/blob/mac_kq/modules/workers/myWorker.js#L171-172)
- [x] Merge kquue based on working example to jscFileWatcher API
- [x] WINNT standalone working example
  - Aysnc fully working, install from [Branch: for-noit-winnt-work Commit: initial.rev104](https://github.com/Noitidart/jscFileWatcher/tree/cc88f3ae8ff13983fd95a60816a7b18a0fea982d) ([code sequence of interest](https://github.com/Noitidart/jscFileWatcher/blob/cc88f3ae8ff13983fd95a60816a7b18a0fea982d/modules/workers/FSWatcherWorker.js#L111-323))
  - Sync version works too but will not be using in jscAPI but to see in action install from [Branch: for-noit-winnt-work Commit: initial.rev98](https://github.com/Noitidart/jscFileWatcher/tree/36d53bc6b19f36e4612658b90260f4d4cbd2c49d) ([code sequence of interest](https://github.com/Noitidart/jscFileWatcher/blob/36d53bc6b19f36e4612658b90260f4d4cbd2c49d/modules/workers/FSWatcherWorker.js#L110-198))
- [x] Merge WINNT based on working example to jscFileWatcher API
- [ ] Fill bodies of the .close and .removePath of jscAPI, the os-api it will use should already be available in the standalone examples created
  - Ensure proper termination of workers see here for tips from @yoric: [chat-with-yoric-on-terminating-promiseworker.md](https://gist.github.com/Noitidart/744c702f44b4d65fcc22)
- [ ] Test to see if FSEvents on OSX < 10.7 triggers on directory even if file is overwritten, hopefully it does otherwise we have no slution for OSX < 10.7 other then hybrid kqueue and/or recursive kqueue (we dont ever plan to do recursive kqueue though its just too much overhead, dev-user should just pick the files they want to watch with hybird kqueue)
- [ ] Use GIO for file watching, for linux/*bsd/solaris
  - This will replace iNotifiy and kqueue and ports on solaris
- [x] OSX >= 10.7 FSEventFramework standalone working example
  - Working [Branch: for-osx10.7-FSEventFramework-work Commit: lib correct for < 10.10](https://github.com/Noitidart/jscFileWatcher/tree/for-osx10.7-FSEventFramework-work) ([code of interest](https://github.com/Noitidart/jscFileWatcher/blob/for-osx10.7-FSEventFramework-work/modules/workers/FSWatcherWorker.js#L180-240))
- [x] Merge OSX >= 10.7 FSEventFramework based on working example to jscFileWatcher API

Future work:
- [ ] Make kqueue hybird
  - See comment: https://github.com/Noitidart/jscFileWatcher/issues/4#issuecomment-98409222

Deprecated future work that we can do for learning:
- [ ] SunOS standalone working example and merge to jscAPI
  - See comment: https://github.com/Noitidart/jscFileWatcher/issues/4#issuecomment-98409222

**Comment by Noitidart** [comment]
looks like i cant assign multipl to a task. but i was just trying to assign both of us to it. github doesnt allow it so i unassigned us both :P

**Comment by P0lip** [comment]
Haha ok :D

**Comment by Noitidart** [comment]
standalone example of FSEventFramework done just need to flesh out the callback, more info here: https://bugzilla.mozilla.org/show_bug.cgi?id=992895#c10

techqniue for merging to jscAPI:
on create start the pollWatcher thread, on init call `CFRunLoopGetCurrent` and return. then create the array etc and call `CFRunLoopRun`. this should not block, like in the standalone example, once you run CFRunLoopRun it doesnt execute the functions after it (notice the `console.log('run loop run started!!!');` never triggers). this is becaues im using the same thread for the loop in stand alone example. i strongly suspect with this technique, and the pointer pointing to thread of pollWatcher, it will not block.

**Comment by Noitidart** [comment]
### kqueue moved to backburner

###### Plan for OSX < 10.7 & reason to not deprecate kqueue for iOS & Solaris

Due to kqueue issue #19 @P0lip and I discussed it. It is impossible for a directory to trigger a notification when a file within is modified by certain methods.  We did not want to recursively add each file to the kqueue. Therefore we came up with two options:
1. Switch to GioFileMonitor
2. Make kqueue dir/file hybrid. Tell dev-users that the API when using kqueue, if watching directory, then it will only trigger on SOME contents-modified events but NOT ALL. If they want to watch for a specific file they should add the file. And in our code we would handle it different based on is dir or file.
3. Recursively add children files of directory into kqueue dir/file hybrid

So the decision was to do 1 and 2 BUT NOT 3. We will keep it around as we may want iOS support in future and iOS only has kqueue, so the 2nd option has to be completed sometime. 3 has way too much overhead, devuser should just pick which files they want to watch.

For desktop OS's we're moving to Gio for fill watching as *BSD, Solaris are gtk2 on Services.appinfo.widgetToolkit. And for OSX < 10.7 @P0lip is downloading OSX 10.6 right now and we're going to test to see if FSEvents triggers on directory when file is overwritten (the way that was not triggering event on dir with kqueue), if it does then we can use the dir stat method of kqueue on OSX <10.7; if it does not trigger then we're stuck in same mud we had with kqueue in #19. It is stated that in OSX <10.7 FSEvents does not tell which file in directory change but it does trigger on file see here: https://bugzilla.mozilla.org/show_bug.cgi?id=992895#c7

We still hope to write up the SunOS method for learning purposes. So that is also getting put on the backburner as Solaris has gtk2 for widgetToolkit so Gio get's used here as well.

**Comment by Noitidart** [comment]
This the info for Solaris file watchers:
- https://solarisrants.wordpress.com/2013/07/24/solaris-file-event-notification/ - FEN File Events Notification
- http://savannah.nongnu.org/task/?2058 - FAM File Alteration Monitor

**Comment by Noitidart** [comment]
Not a bug or anything. And this tracker is no longer relevant. So closing this out.
